sudo: false

language:
  - c
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - pip install --user urllib3[secure] cpp-coveralls

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests/crypto_test/run_tests

after_success:
  - coveralls -r .. -b . --verbose -e tests -e build -e '<built-in>' --gcov-options '\-lp'

notifications:
  email: false
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
