sudo: true

language:
  - c
  - cpp
  - node_js

compiler:
  - gcc

node_js:
  - "iojs"

env:
  - SRC=crypto

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get update
  - sudo apt-get install -y lcov

before_script:
  - sudo npm -g install coveralls

script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ..
  - make -j5
  - lcov --zerocounters --directory $SRC
  - lcov --capture --initial --directory $SRC --output-file app
  - ./tests/crypto_test/run_tests

after_success:
  - lcov --no-checksum --directory $SRC --capture --output-file app.info
  - node /usr/lib/node_modules/coveralls/bin/coveralls.js < app.info

notifications:
  email: false
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
